theme: jekyll-theme-time-machine

title: "david232818"
name: Kown Young Jung
description: NULL
url: "https://david232818.github.io"

permalink: /:title/
paginate: 5
paginate_path: /page:num/
timezone: Asia/Seoul

futrue: true
published: true